### ISSUE TITLE
SeaBIOS ✅ OVMF ✅

### ISSUE THREAD

**Issue by limbo127** [tenclass/mvisor#58]
Hello, 
Readme says ovmf ( efi ) is ok but nothting in code or example to show it
Regards, 
Nicolas Prochazka

**Comment by 78** [comment]
This is a sample config to use OVMF for Windows (nothing changed but bios file):

```yaml
name: OVMF sample
base: q35.yaml

machine:
  memory: 4G
  vcpu: 8
  debug: No
  hypervisor: Yes
  bios: ../share/OVMF.fd

objects:
  - name: cmos
    # gmtime for linux, localtime for windows
    rtc: localtime

  - class: qxl
  - class: spice-agent
  - class: qemu-guest-agent
  - class: usb-tablet
  - class: usb-keyboard
  - class: pvpanic

  - class: virtio-network
    mac: 00:50:00:11:22:33

  - class: virtio-block
    image: /data/images/win10.qcow2
    snapshot: Yes
```

For macOS,

```yaml
name: macOS-Sonoma
base: q35.yaml

machine:
  memory: 4G
  vcpu: 8
  debug: No
  hypervisor: Yes
  bios: /data/OSX-KVM/OVMF_CODE.fd
  cpuid:
    vendor: GenuineIntel

objects:
  - name: cmos
    # gmtime for linux, localtime for windows
    rtc: gmtime
  - class: vga
  - class: usb-tablet
  - class: usb-keyboard
  
  - class: virtio-network
    mac: 00:50:00:11:22:33

  - class: apple-smc
    osk: "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"

  - class: virtio-block
    image: /data/OSX-KVM/OpenCore/OpenCore.qcow2
    snapshot: Yes

  - class: virtio-block
    image: /data/OSX-KVM/BaseSystem.img
    readonly: Yes

  - class: virtio-block
    image: /data/OSX-KVM/mac_hdd.qcow2
    snapshot: Yes
```
