### ISSUE TITLE
Help: dGPU not being used with libvirtio-vgpu

### ISSUE THREAD

**Issue by jobs-git** [tenclass/mvisor#69]
Host: Ubuntu 24.04
Guest: Win 10 (driver installed)
Kernel: 6.8.0-51-generic
Nvidia-driver: 550.127.05

I have an Nvidia 4070 RTX dGPU at /dev/dri/render129 on pcie slot. Host monitor is connected iGPU AMDGPU from Ryzen 7600. Virglrenderer has been patch and installed based on https://github.com/tenclass/mvisor-win-vgpu-driver readme.

Below is the configuration that I use:

```yaml
name: Default configuration
base: q35.yaml

machine:
  memory: 4G
  vcpu: 4
  # Set vcpu thread priority value [-20, 19]
  # A higher value means a lower priority
  priority: 1
  # Turn on BIOS output and performance measurement
  debug: No
  # Turn on hypervisor to lower CPU usage (Hyper-V is used for Windows)
  hypervisor: Yes

objects:
  - name: cmos
    # gmtime for linux, localtime for windows
    rtc: localtime

  - class: qxl
  - class: spice-agent
  - class: usb-tablet

  - class: virtio-network
    mac: 00:50:00:11:22:33
    map: tcp:0.0.0.0:8022-:22

  - class: ata-cdrom 
    image: /home/vgpu-guest-driver-build-master.iso
  
  - class: ata-cdrom
    image: /home/virtio-win-0.1.266.iso

  - class: ata-disk
    image: /home/win10virgl.qcow2
    snapshot: No

  - class: virtio-vgpu
    memory: 1G
    staging: yes
    blob: Yes
    node: /dev/dri/renderD129
```

I was suspecting it needs prime so I did:

`DRI_PRIME=1 ./build/mvisor -c config/sample.yaml -vnc 5900`

But I get this error:

`failed to load driver: nouveau`
