### ISSUE TITLE
Can't boot existing UEFI Windows 10 image

### ISSUE THREAD

**Issue by hardcore-sushi** [tenclass/mvisor#73]
I converted a UEFI Windows 10 image created using virt-manager with:

```
qemu-img convert -O qcow2 /var/lib/libvirt/images/Windows10.qcow2 Windows10.qcow2
```

When I booted with mvisor I got this error:
![Image](https://github.com/user-attachments/assets/3fe689a3-47d6-4374-ba06-414863b40caa)

Here my configs:

q35.yaml:
```yaml
name: q35-machine

machine:
  memory: 4G
  vcpu: 4
  #bios: share/bios-256k.bin
  bios: /usr/share/ovmf/OVMF.fd

objects:
# Use the old name pci-host instead of q35-host for compatibility
  - class: q35-host
  - class: kvm-irqchip
  - class: kvm-clock
  - class: firmware-config
  - class: debug-console
  - class: dummy-device

# PCI devices connected to PCI Host
  - class: ich9-hda
  - class: ich9-lpc
  - class: ich9-ahci

# I/O devices connected to ICH9 LPC
  - class: cmos
  - class: ps2

# codec device connected to ICH9 HDA
  - class: hda-duplex
```

config.yaml:
```yaml
name: Default configuration
base: q35.yaml

machine:
  memory: 4G
  vcpu: 8
  priority: 1
  debug: No
  hypervisor: Yes
  bios: /usr/share/ovmf/OVMF.fd

objects:
  - name: cmos
    rtc: localtime

  - class: qxl
    rom: share/vgabios-qxl.bin
  - class: spice-agent
  - class: usb-tablet

  - class: virtio-network
    mac: 00:50:00:11:22:33

  - class: virtio-block
    image: Windows10.qcow2
    snapshot: No

  - class: ata-cdrom
    image: virtio-win-0.1.266.iso

  - class: virtio-vgpu
    memory: 1G
    staging: No
    blob: No
    node: /dev/dri/renderD128
```

Now I can't boot anymore:

![Image](https://github.com/user-attachments/assets/18f54ade-6c6c-4778-825d-4f4b1f58232f)

Host kernel version is `5.15.0-133-generic`.

**Comment by hardcore-sushi** [comment]
I fixed the issue by recreating the image and replacing `virtio-block` with `ata-disk`. However, when adding virtio-fs, mvisor won't boot:

```
[0.005] devices/virtio/virtio_pci.cc:500 ReadCommonConfig() panic-error: unhandled read offset=0x16 size=2 errno=4, Interrupted system call
[0.191] core/vcpu.cc:621 Process() debug: vcpu 0 exception: Panic
```
```yaml
  - class: virtio-fs
    path: share
    disk_name: share
```
